
package no.differitas._2006._09.messaging.sms;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SmsCallbackService", targetNamespace = "http://differitas.no/2006/09/messaging/sms")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    com.microsoft.schemas._2003._10.serialization.ObjectFactory.class,
    no.differitas._2006._09.messaging.sms.ObjectFactory.class
})
public interface SmsCallbackService {


    /**
     * 
     * @param parameters
     * @return
     *     returns no.differitas._2006._09.messaging.sms.DeliverRsp
     * @throws ServerFault_Exception
     * @throws ValidationFault_Exception
     */
    @WebMethod(operationName = "DeliverMessage", action = "http://differitas.no/2006/09/messaging/sms/SmsCallbackService/DeliverMessage")
    @WebResult(name = "DeliverRsp", targetNamespace = "http://differitas.no/2006/09/messaging/sms", partName = "parameters")
    public DeliverRsp deliverMessage(
        @WebParam(name = "DeliverReq", targetNamespace = "http://differitas.no/2006/09/messaging/sms", partName = "parameters")
        DeliverReq parameters)
        throws ServerFault_Exception, ValidationFault_Exception
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns no.differitas._2006._09.messaging.sms.DeliveryReportRsp
     * @throws ServerFault_Exception
     * @throws ValidationFault_Exception
     */
    @WebMethod(operationName = "DeliverReport", action = "http://differitas.no/2006/09/messaging/sms/SmsCallbackService/DeliverReport")
    @WebResult(name = "DeliveryReportRsp", targetNamespace = "http://differitas.no/2006/09/messaging/sms", partName = "parameters")
    public DeliveryReportRsp deliverReport(
        @WebParam(name = "DeliveryReportReq", targetNamespace = "http://differitas.no/2006/09/messaging/sms", partName = "parameters")
        DeliveryReportReq parameters)
        throws ServerFault_Exception, ValidationFault_Exception
    ;

}
