
package no.differitas._2006._09.messaging.sms;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SmsService", targetNamespace = "http://differitas.no/2006/09/messaging/sms")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    com.microsoft.schemas._2003._10.serialization.ObjectFactory.class,
    no.differitas._2006._09.messaging.sms.ObjectFactory.class
})
public interface SmsService {


    /**
     * 
     * @param parameters
     * @return
     *     returns no.differitas._2006._09.messaging.sms.SubmitRsp
     * @throws SmsServiceSubmitServerFaultFaultMessage
     * @throws SmsServiceSubmitValidationFaultFaultMessage
     */
    @WebMethod(operationName = "Submit", action = "http://differitas.no/2006/09/messaging/sms/SmsService/Submit")
    @WebResult(name = "SubmitRsp", targetNamespace = "http://differitas.no/2006/09/messaging/sms", partName = "parameters")
    public SubmitRsp submit(
        @WebParam(name = "SubmitReq", targetNamespace = "http://differitas.no/2006/09/messaging/sms", partName = "parameters")
        SubmitReq parameters)
        throws SmsServiceSubmitServerFaultFaultMessage, SmsServiceSubmitValidationFaultFaultMessage
    ;

}
