
package no.differitas._2006._09.messaging.sms;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "ServerFault", targetNamespace = "http://differitas.no/2006/09/messaging/sms")
public class SmsServiceSubmitServerFaultFaultMessage
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private ServerFault faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public SmsServiceSubmitServerFaultFaultMessage(String message, ServerFault faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public SmsServiceSubmitServerFaultFaultMessage(String message, ServerFault faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: no.differitas._2006._09.messaging.sms.ServerFault
     */
    public ServerFault getFaultInfo() {
        return faultInfo;
    }

}
