
package no.differitas._2015._10.coveragearea;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CoverageAreaService", targetNamespace = "http://differitas.no/2015/10/coveragearea")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CoverageAreaService {


    /**
     * 
     * @param parameters
     * @return
     *     returns no.differitas._2015._10.coveragearea.CoverageAreaRsp
     * @throws ValidationFaultMessage
     * @throws ServerFaultMessage
     */
    @WebMethod(operationName = "Coverage", action = "http://differitas.no/2015/10/coveragearea/CoverageAreaService/Coverage")
    @WebResult(name = "CoverageAreaRsp", targetNamespace = "http://differitas.no/2015/10/coveragearea", partName = "parameters")
    public CoverageAreaRsp coverage(
        @WebParam(name = "CoverageAreaReq", targetNamespace = "http://differitas.no/2015/10/coveragearea", partName = "parameters")
        CoverageAreaReq parameters)
        throws ServerFaultMessage, ValidationFaultMessage
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns no.differitas._2015._10.coveragearea.PlacenameRsp
     * @throws ValidationFaultMessage
     * @throws ServerFaultMessage
     */
    @WebMethod(operationName = "Placename", action = "http://differitas.no/2015/10/coveragearea/CoverageAreaService/Placename")
    @WebResult(name = "PlacenameRsp", targetNamespace = "http://differitas.no/2015/10/coveragearea", partName = "parameters")
    public PlacenameRsp placename(
        @WebParam(name = "PlacenameReq", targetNamespace = "http://differitas.no/2015/10/coveragearea", partName = "parameters")
        PlacenameReq parameters)
        throws ServerFaultMessage, ValidationFaultMessage
    ;

}
