
package no.differitas._2015._10.coveragearea;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "ValidationFault", targetNamespace = "http://differitas.no/2015/10/coveragearea")
public class ValidationFaultMessage
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private ValidationFault faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public ValidationFaultMessage(String message, ValidationFault faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public ValidationFaultMessage(String message, ValidationFault faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: no.differitas._2015._10.coveragearea.ValidationFault
     */
    public ValidationFault getFaultInfo() {
        return faultInfo;
    }

}
